name: food_share
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

  easy_localization: ^3.0.7
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  flutter_bloc: ^8.1.3
  auto_route: ^8.1.3
  another_flushbar: ^1.12.30
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  injectable: ^2.4.1
  get_it: ^7.7.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1+2
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.2
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo-smal.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo-small.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/home.jpg
    - assets/images/placeholder.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
