// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_p_vQvHW9telZtOxsJsQEckQQlr-7u7Y',
    appId: '1:729221675168:web:a4da180788e65e1f0c31c5',
    messagingSenderId: '729221675168',
    projectId: 'food-share-ddc78',
    authDomain: 'food-share-ddc78.firebaseapp.com',
    storageBucket: 'food-share-ddc78.appspot.com',
    measurementId: 'G-CFMX8EZJ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9R1ySaDGkYnwJT1XjtAYw0HAip_recrs',
    appId: '1:729221675168:android:97039196428a8f910c31c5',
    messagingSenderId: '729221675168',
    projectId: 'food-share-ddc78',
    storageBucket: 'food-share-ddc78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2DsqJE2s9IKYFHEfpUtBXWENJv6qFjY',
    appId: '1:729221675168:ios:3cfec1ffefe7ac540c31c5',
    messagingSenderId: '729221675168',
    projectId: 'food-share-ddc78',
    storageBucket: 'food-share-ddc78.appspot.com',
    iosBundleId: 'com.example.foodShare',
  );
}
